version: "3"

networks:
  default:
    external:
      name: messages_default

services:
  phpstorm:
    container_name: messages_phpstorm
    build:
      context: docker/php
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 174.70.1.3
      DB_PORT: 3306
      DB_DATABASE: messages
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - .:/opt/messages:cached
    networks:
      - default
